#!/usr/bin/env python3
"""
Analyze Zelda 1 underworld enemy CHR pattern blocks.

Each NES 8x8 2bpp pattern tile is 16 bytes.

Outputs:
    research/enemy-chr-analysis.md
    research/enemy-chr-tiles.csv
"""

from __future__ import annotations

import csv
import hashlib
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "bin" / "dat"
RESEARCH_DIR = ROOT / "research"

BLOCKS = {
    "common_uw": "PatternBlockUWSP.dat",
    "regular_127": "PatternBlockUWSP127.dat",
    "regular_358": "PatternBlockUWSP358.dat",
    "regular_469": "PatternBlockUWSP469.dat",
    "boss_1257": "PatternBlockUWSPBoss1257.dat",
    "boss_3468": "PatternBlockUWSPBoss3468.dat",
    "boss_9": "PatternBlockUWSPBoss9.dat",
}

EXPECTED_SIZES = {
    "common_uw": 0x0100,
    "regular_127": 0x0220,
    "regular_358": 0x0220,
    "regular_469": 0x0220,
    "boss_1257": 0x0400,
    "boss_3468": 0x0400,
    "boss_9": 0x0400,
}

TILE_SIZE = 16


def split_tiles(data: bytes) -> list[bytes]:
    if len(data) % TILE_SIZE != 0:
        raise ValueError(
            f"Block size {len(data)} is not divisible by {TILE_SIZE}"
        )

    return [
        data[offset : offset + TILE_SIZE]
        for offset in range(0, len(data), TILE_SIZE)
    ]


def short_hash(tile: bytes) -> str:
    return hashlib.sha1(tile).hexdigest()[:12]


def load_blocks() -> dict[str, list[bytes]]:
    loaded: dict[str, list[bytes]] = {}

    for block_name, filename in BLOCKS.items():
        path = DATA_DIR / filename

        if not path.exists():
            raise FileNotFoundError(f"Missing pattern block: {path}")

        data = path.read_bytes()
        expected = EXPECTED_SIZES[block_name]

        if len(data) != expected:
            raise ValueError(
                f"{filename}: expected {expected} bytes "
                f"(${expected:04X}), found {len(data)}"
            )

        loaded[block_name] = split_tiles(data)

    return loaded


def build_occurrence_map(
    blocks: dict[str, list[bytes]],
) -> dict[bytes, list[tuple[str, int]]]:
    occurrences: dict[bytes, list[tuple[str, int]]] = defaultdict(list)

    for block_name, tiles in blocks.items():
        for tile_index, tile in enumerate(tiles):
            occurrences[tile].append((block_name, tile_index))

    return occurrences


def write_csv(
    blocks: dict[str, list[bytes]],
    occurrences: dict[bytes, list[tuple[str, int]]],
) -> Path:
    output = RESEARCH_DIR / "enemy-chr-tiles.csv"

    with output.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(
            [
                "block",
                "tile_index_decimal",
                "tile_index_hex",
                "sha1_short",
                "identical_copy_count",
                "identical_locations",
            ]
        )

        for block_name, tiles in blocks.items():
            for tile_index, tile in enumerate(tiles):
                locations = occurrences[tile]

                writer.writerow(
                    [
                        block_name,
                        tile_index,
                        f"${tile_index:02X}",
                        short_hash(tile),
                        len(locations),
                        "; ".join(
                            f"{name}:${index:02X}"
                            for name, index in locations
                        ),
                    ]
                )

    return output


def matching_indexes(
    first: list[bytes],
    second: list[bytes],
) -> list[int]:
    return [
        index
        for index, (left, right) in enumerate(zip(first, second))
        if left == right
    ]


def differing_indexes(
    first: list[bytes],
    second: list[bytes],
) -> list[int]:
    return [
        index
        for index, (left, right) in enumerate(zip(first, second))
        if left != right
    ]


def format_indexes(indexes: list[int]) -> str:
    if not indexes:
        return "None"

    return ", ".join(f"${index:02X}" for index in indexes)


def write_markdown(
    blocks: dict[str, list[bytes]],
    occurrences: dict[bytes, list[tuple[str, int]]],
) -> Path:
    output = RESEARCH_DIR / "enemy-chr-analysis.md"

    all_tile_instances = sum(len(tiles) for tiles in blocks.values())
    unique_tiles = len(occurrences)
    duplicated_instances = all_tile_instances - unique_tiles

    regular_names = ["regular_127", "regular_358", "regular_469"]
    boss_names = ["boss_1257", "boss_3468", "boss_9"]

    lines: list[str] = [
        "# Z1 Dojo Enemy CHR Analysis",
        "",
        "Generated by `tools/analyze_enemy_chr.py`.",
        "",
        "## Pattern Block Summary",
        "",
        "| Block | Bytes | Tiles |",
        "|---|---:|---:|",
    ]

    for block_name, tiles in blocks.items():
        byte_count = len(tiles) * TILE_SIZE
        lines.append(
            f"| `{block_name}` | ${byte_count:04X} "
            f"({byte_count}) | {len(tiles)} |"
        )

    lines.extend(
        [
            "",
            "## Global Deduplication",
            "",
            f"- Total tile instances: **{all_tile_instances}**",
            f"- Unique tile bitmaps: **{unique_tiles}**",
            f"- Duplicate instances: **{duplicated_instances}**",
            "",
            "This counts identical 16-byte tile bitmaps across every "
            "regular, boss, and common underworld block.",
            "",
            "## Regular Enemy Pack Comparisons",
            "",
        ]
    )

    for left_index, left_name in enumerate(regular_names):
        for right_name in regular_names[left_index + 1 :]:
            same = matching_indexes(blocks[left_name], blocks[right_name])
            different = differing_indexes(
                blocks[left_name], blocks[right_name]
            )

            lines.extend(
                [
                    f"### `{left_name}` vs. `{right_name}`",
                    "",
                    f"- Matching indexes: **{len(same)} / "
                    f"{len(blocks[left_name])}**",
                    f"- Differing indexes: **{len(different)}**",
                    f"- Matching: {format_indexes(same)}",
                    f"- Different: {format_indexes(different)}",
                    "",
                ]
            )

    lines.extend(
        [
            "## Boss Pack Comparisons",
            "",
        ]
    )

    for left_index, left_name in enumerate(boss_names):
        for right_name in boss_names[left_index + 1 :]:
            same = matching_indexes(blocks[left_name], blocks[right_name])
            different = differing_indexes(
                blocks[left_name], blocks[right_name]
            )

            lines.extend(
                [
                    f"### `{left_name}` vs. `{right_name}`",
                    "",
                    f"- Matching indexes: **{len(same)} / "
                    f"{len(blocks[left_name])}**",
                    f"- Differing indexes: **{len(different)}**",
                    f"- Matching: {format_indexes(same)}",
                    f"- Different: {format_indexes(different)}",
                    "",
                ]
            )

    lines.extend(
        [
            "## Most Reused Tiles",
            "",
            "| Copies | Hash | Locations |",
            "|---:|---|---|",
        ]
    )

    reused = sorted(
        (
            (len(locations), tile, locations)
            for tile, locations in occurrences.items()
            if len(locations) > 1
        ),
        reverse=True,
        key=lambda item: item[0],
    )

    for copy_count, tile, locations in reused[:40]:
        location_text = ", ".join(
            f"`{name}:${index:02X}`" for name, index in locations
        )

        lines.append(
            f"| {copy_count} | `{short_hash(tile)}` | {location_text} |"
        )

    lines.extend(
        [
            "",
            "## Next Research Step",
            "",
            "Map object types and animation descriptors to the tile indexes "
            "listed in this report. That will reveal each enemy's complete "
            "graphics dependency set.",
            "",
        ]
    )

    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def main() -> None:
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)

    blocks = load_blocks()
    occurrences = build_occurrence_map(blocks)

    markdown_path = write_markdown(blocks, occurrences)
    csv_path = write_csv(blocks, occurrences)

    print("Enemy CHR analysis complete.")
    print(f"Markdown: {markdown_path.relative_to(ROOT)}")
    print(f"CSV:      {csv_path.relative_to(ROOT)}")

    for block_name, tiles in blocks.items():
        print(
            f"{block_name:12} "
            f"{len(tiles) * TILE_SIZE:4} bytes "
            f"{len(tiles):3} tiles"
        )


if __name__ == "__main__":
    main()